#! /usr/bin/python3

import cgi
import json
import sqlite3

SMILE = 0
PURE = 1
COOL = 2

Type = {
  'スマイル' : SMILE,
  'ピュア' : PURE,
  'クール' : COOL
}

def parse(string):
  strings = string.split(',')
  major = strings[0]
  minor = ''
  for s in strings[1:]:
    minor += s
  return (major, minor)

try:
  print('content-type:application/json')
  print('')

  form = cgi.FieldStorage()

  sort = {
    'n' : '_no',
    'r' : 'rarity',
    's' : 'final_max_smile',
    'p' : 'final_max_pure',
    'c' : 'final_max_cool',
    't' : 'type'
  }.get(form.getvalue('s'), '_no')

  order = {
    'a' : 'ASC',
    'd' : 'DESC'
  }.get(form.getvalue('o'), 'ASC')

  conn = sqlite3.connect('sif.db')
  c = conn.cursor()
  query = 'SELECT * FROM member ORDER BY %s %s' % (sort, order)
  c.execute(query)
  data = []
  for row in c:
    # null value to empty string
    r = list(row)
    for i in range(0, len(r)):
      if (r[i] == None):
        r[i] = ''

    # parse name
    name, description = parse(r[2])

    # parse skill
    skill = parse(r[16])

    # parse center skill
    center_skill_name = parse(r[17])
    center_skill_effect = {
      'スマイルパワー' : (SMILE, 0.03),
      'ピュアパワー' : (PURE, 0.03),
      'クールパワー' : (COOL, 0.03),
      'スマイルハート' : (SMILE, 0.06),
      'ピュアハート' : (PURE, 0.06),
      'クールハート' : (COOL, 0.06),
      'スマイルプリンセス' : (SMILE, 0.09),
      'ピュアエンジェル' : (PURE, 0.09),
      'クールエンプレス' : (COOL, 0.09),
    }.get(center_skill_name[0], (-1, 0.0))

    data.append({
      'number' : r[0],
      'img' : r[1],
      'charaName' : parse(r[2]),
      'type' : Type[r[3]],
      'hp' : (r[4], r[8], r[12]),
      'smile' : (r[5], r[9], r[13]),
      'pure' : (r[6], r[10], r[14]),
      'cool' : (r[7], r[11], r[15]),
      'skill' : parse(r[16]),
      'centerSkill' : (center_skill_name[0], center_skill_name[1], center_skill_effect[0], center_skill_effect[1]),
      'rarity' : r[18]
    })
  print(json.dumps(data))
  c.close()
except Exception as e:
  print(e)

